import json,re,html
import argparse
import shutil
from pathlib import Path
parser = argparse.ArgumentParser(description='Build the static literature notebook.')
parser.add_argument('--publish-root', action='store_true', help='Also copy the static site into the parent repository root for GitHub Pages.')
args = parser.parse_args()
ROOT=Path(__file__).parent
E=lambda s:html.escape(str(s),quote=True)
raw=json.loads((ROOT/'data/rdf-records.json').read_text())
def part(s,start,end):return s.split(start,1)[-1].split(end,1)[0].strip()
papers=[]
for p in raw:
 n=int(p['id'].split('_')[1]); notes=p['notes']
 papers.append(dict(authors=p.get('authors',[]),id=p['id'],title=p['title'],year=p['date'][:4],url=p['url'],group=p['tags'][1],method=part(notes,'Method and idea:','Achievements and evidence:'),achievement=part(notes,'Achievements and evidence:','Remaining gap — review assessment:'),gap=part(notes,'Remaining gap — review assessment:','Review year/version:'),overview='',evidence='RDF evidence; not rechecked',setting='Not independently checked',environment='Low-gravity research; Earth-based tests' if n>=44 else 'Earth-oriented; see evidence',order='Not independently checked',architecture='See method description',origin='Supplied RDF',verification='Imported review notes; primary source not independently checked in this pass.',sources=[],video=''))
if (ROOT/'data/updates.json').exists():
 updates=json.loads((ROOT/'data/updates.json').read_text())
 for p in papers:p.update(updates.get(p['id'],{}))
if (ROOT/'data/additions.json').exists():papers+=json.loads((ROOT/'data/additions.json').read_text())
(ROOT/'dist/papers.json').write_text(json.dumps(papers,indent=2,ensure_ascii=False))
def link(url,label):return f'<a href="{E(url)}" target="_blank" rel="noopener noreferrer">{E(label)}</a>'
def card(p):
 overview=p.get('overview') or 'This record studies '+p['group'].lower()+'. The imported review characterizes the approach as '+p['method']+'.'
 sources=' · '.join(link(s['url'],s['label']) for s in p.get('sources',[]))
 video=link(p['video'],p.get('videoLabel','Video / author demonstrations')) if p.get('video') else '<span class="muted">Video not verified</span>'
 return f'''<details class="paper" id="{E(p['id'])}"><summary><span class="paper-year">{E(p['year'])}</span><span class="paper-main"><span class="paper-title">{E(p['title'])}</span><span class="tags"><span>{E(p['method'])}</span><span>{E(p['evidence'])}</span></span></span><span class="expand" aria-hidden="true">+</span></summary><div class="paper-body"><div class="provenance">{E(p['origin'])} · {E(p['verification'])}</div><p class="mini-note">{E(', '.join(p.get('authors',[])))}</p><p>{E(overview)}</p><dl class="specs"><div><dt>Evidence / setting</dt><dd>{E(p['setting'])}</dd></div><div><dt>Environment</dt><dd>{E(p['environment'])}</dd></div><div><dt>Dynamics model</dt><dd>{E(p['order'])}</dd></div><div><dt>Architecture</dt><dd>{E(p['architecture'])}</dd></div></dl><div class="findings"><section><h4>What is achieved</h4><p>{E(p['achievement'])}</p></section><section><h4>What remains unestablished</h4><p>{E(p['gap'])}</p><small>Review assessment of scope, unless stated otherwise.</small></section></div><div class="resources">{link(p['url'],'Read paper')} {video}</div>{f'<p class="source-line">Evidence sources: {sources}</p>' if sources else ''}</div></details>'''
groups=list(dict.fromkeys(p['group'] for p in papers))
slugs={g:'group-'+str(i+1) for i,g in enumerate(groups)}
head='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Vishnu Joshi’s AI-generated literature notebook. Evidence, methods and open questions in locomotion, manipulation and robotic woodworking."><link rel="icon" href="{prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{prefix}style.css"><title>{title} · Vishnu Joshi</title></head><body><a class="skip" href="#main">Skip to content</a>'''
footer='<footer><span>Vishnu Joshi · Literature notebook</span><span>AI-generated review · Checked 29 September 2026</span></footer>'
from manipulation import build_manipulation
manipulation_count=build_manipulation(ROOT,head,footer)
home=head.format(prefix='./',title='Literature notebook')+f'''<div class="home-wrap"><header class="top"><a class="brand" href="./">VJ<span> / LITERATURE NOTEBOOK</span></a><span class="edition">RESEARCH NOTES / 02</span></header><main id="main"><section class="intro"><p class="eyebrow">A place to begin</p><h1>Hi, I am<br>Vishnu Joshi.</h1><p class="intro-copy">This is an AI-generated website that helps do the initial literature review for the projects I want to work on or am probably working on.</p></section><section class="projects"><div class="section-head"><h2>Projects</h2><span>02 projects</span></div><a class="project-link" href="./quadruped/"><span class="project-number">01</span><div><p class="eyebrow">Robotics / Locomotion & control</p><h3>Quadruped acrobatics<br>& pronking</h3><p>From repeated hops to aerial maneuvers. What works on hardware, how it is controlled, and where the research is still open.</p><div class="project-meta">{len(papers)} papers &nbsp; · &nbsp; Methods & evidence &nbsp; · &nbsp; Earth & low gravity</div></div><span class="project-action">Open review</span></a><a class="project-link" href="./manipulation/"><span class="project-number">02</span><div><p class="eyebrow">Robotics / Contact, learning & fabrication</p><h3>Robotic<br>manipulation</h3><p>Vision, force, proprioception and learned action. From dexterous hands and household tasks to a dedicated woodworking workflow.</p><div class="project-meta">{manipulation_count} papers &nbsp; · &nbsp; Through 29 Sep 2026 &nbsp; · &nbsp; Hardware evidence</div></div><span class="project-action">Open review</span></a></section></main>{footer}</div></body></html>'''
(ROOT/'dist/index.html').write_text(home)
nav=''.join(f'<a href="#{slugs[g]}">{E(g)}<span>{sum(p["group"]==g for p in papers):02}</span></a>' for g in groups)
body=''.join(f'<section class="paper-group" id="{slugs[g]}"><div class="section-head"><h2>{E(g)}</h2><span>{sum(p["group"]==g for p in papers):02} papers</span></div>'+''.join(card(p) for p in papers if p['group']==g)+'</section>' for g in groups)
synthesis=(ROOT/'data/synthesis.html').read_text() if (ROOT/'data/synthesis.html').exists() else ''
review=head.format(prefix='../',title='Quadruped acrobatics & pronking')+f'''<header class="top review-top"><a class="brand" href="../">VJ<span> / LITERATURE NOTEBOOK</span></a><a href="../">All projects</a></header><div class="review-layout"><aside><p class="eyebrow">Project 01</p><h2>Quadruped<br>acrobatics</h2><nav aria-label="Review sections"><a class="nav-major" href="#papers">Paper library<span>{len(papers)}</span></a>{nav}<div class="nav-divider"></div><a href="#gaps">Hardware & research gaps</a><a href="#methods">Methods explained</a><a href="#transfer">Bipedal connections</a><a href="#scope">Scope & sources</a></nav><p class="sidebar-note">A research starting point.<br>Claims stay close to their evidence.</p></aside><main id="main"><div class="review-heading"><p class="eyebrow">Robotics / Literature review</p><h1>Quadruped acrobatics<br><em>& pronking.</em></h1><p>Read the result. Check the hardware. Find the next question.</p><div class="review-meta"><span>{len(papers)} papers</span><span>45 RDF records + {len(papers)-45} additions</span><span>29 Sep 2026</span></div></div><div class="brief"><strong>The research question</strong><p>How can a quadruped repeatedly take off, control its flight, and land ready for the next movement—on terrain it does not know?</p><a href="#gaps">Read the evidence & gap assessment</a></div><section id="papers"><div class="library-head"><h2>Paper library</h2><p>Expand a paper for its method, evidence, achievements and limits.</p></div>{body}</section>{synthesis}<section class="essay" id="scope"><p class="eyebrow">Review protocol</p><h2>Scope & sources</h2><p>This is a focused narrative survey, not an exhaustive systematic review. The supplied Zotero RDF contributes 45 records. Additional searches cover pronking, jumping, landing, parkour, generative control, bipedal skills and low-gravity locomotion. Primary papers, author project pages, university repositories and ESA materials support the checked records.</p><p>Every card separates the imported record from independently checked evidence. “Abstract checked” supports only abstract-level claims; it does not mean the full experimental record was audited. “Not independently checked” is intentional. Missing evidence is not proof that a capability does not exist. Gap statements are review inferences, not universal novelty claims.</p><p>Dates on imported records follow the RDF and may refer to a journal version rather than the first preprint. Newly added records identify the version in their evidence notes. A lab experiment is real hardware, but does not establish field reliability. Testbeds on Earth do not establish deployment on the Moon or Mars. A linked video is supplementary evidence, not a quantified reliability study.</p><p>The site is a static snapshot, last researched 29 September 2026. Its sources and review data can be updated for future projects.</p></section>{footer}</main></div><script src="../app.js"></script></body></html>'''
(ROOT/'dist/quadruped/index.html').write_text(review)

if args.publish_root:
    for source in (ROOT/'dist').rglob('*'):
        if source.is_file():
            target = ROOT.parent / source.relative_to(ROOT/'dist')
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
    (ROOT.parent/'.nojekyll').touch()
