import json
from pathlib import Path
R=Path(__file__).parent; raw=json.loads((R/'data/rdf-records.json').read_text()); U={}
# Evidence imported from the supplied bibliography is explicitly attributed.
sim={1,4,7,21,24,27,30,39}
for p in raw:
 n=int(p['id'].split('_')[1]); U[p['id']]={'evidence':'Simulation · RDF report' if n in sim else 'Hardware · RDF report','setting':'Simulation only, according to supplied review.' if n in sim else 'Physical experiments reported in supplied review; lab/outdoor conditions not independently checked.','order':'Not specified in imported review; model order is not inferred from the use of RL.','architecture':p['notes'].split('Method and idea:')[-1].split('Achievements and evidence:')[0].strip(),'overview':'','environment':'Earth gravity / terrestrial research (RDF context).'}
U['item_32']['evidence']='Evidence pending verification'
for n in [44,45]: U['item_'+str(n)].update(evidence='Earth-based gravity testbed · RDF',environment='Extraterrestrial target; simulation / testbed on Earth.',setting='SpaceBok gravity-emulation experiments; no off-world deployment established.')
def checked(n,**kw):
 p=raw[n-1];U[p['id']].update(verification='Primary abstract checked 29 Sep 2026; remaining scope assessed from the cited evidence.',sources=[{'url':p['url'],'label':'Primary paper / repository'}]);U[p['id']].update(kw)
checked(5,evidence='Hardware + simulation',setting='Physical quadruped hopping and bounding; controlled terrain / drop experiments.',overview='A single optimized demonstration helps exploration before task-driven reinforcement learning improves robustness.',order='Trajectory optimizer supplies a reference; RL executes a learned policy.',architecture='Two-stage imitation-to-task RL; optimized teacher.',verification='Primary full text inspected; imported detailed terrain numbers retained as RDF-reported.')
checked(6,evidence='Hardware',setting='DLR bert; direct learning on the physical elastic quadruped.',overview='Optimize a central pattern generator, then learn feedback corrections directly on the elastic robot.',order='Model-free hardware learning; no explicit planning dynamics.',architecture='CPG gait generator + residual RL.',video='https://araffin.github.io/publication/exploit-bert/',videoLabel='Author page & video')
checked(7,evidence='Simulation',setting='Sagittal elastic quadruped simulation.',overview='Elastic design and nonlinear modes exploit natural oscillations to obtain trotting and pronking.',order='Sagittal nonlinear elastic model.',architecture='Mechanical design + nonlinear modal control.')
checked(8,evidence='Hardware',setting='Real-robot continuous omnidirectional jumping; controlled demonstrations.',overview='A learned residual corrects a hand-designed acceleration controller; whole-body control converts the result into motor commands.',order='Body-level acceleration command + whole-body controller.',architecture='Hierarchical hybrid: residual RL + optimal control.',video='https://sites.google.com/view/learning-to-jump',videoLabel='Project & demonstration videos')
checked(9,evidence='Hardware + simulation',setting='Physical parallel-elastic quadruped; continuous jumping experiments.',overview='Iterative learning updates feedforward commands over repeated hops, without resetting after each repetition.',order='Reduced-order soft anchor model.',architecture='Trajectory optimization + iterative learning control (ILC), not RL.',achievement='Repository abstract reports continuous jumping learned within minutes and robustness across tested terrain types. E-Go robot identification is retained from the supplied review.',verification='DLR abstract checked; full text unavailable in repository. RDF year 2024 reflects journal issue; online publication was 2023.')
checked(10,evidence='Hardware + simulation',setting='Rigid and parallel-elastic quadrupeds; matched laboratory comparisons.',overview='A compliant template separates active motor forces from spring forces to plan several explosive motions.',order='Reduced-order dual-legged actuated SLIP with trunk rotation.',architecture='Two-layer trajectory optimization + singularity-free feedback.')
checked(11,evidence='Hardware',setting='Solo-12 physical experiments with terrain changes and perturbations.',overview='Optimizes longitudinal body motion and the contact sequence together, then improves execution through repetition.',order='Reduced-order 2D single rigid body.',architecture='Contact-implicit optimal planning + ILC.')
checked(14,evidence='Hardware',setting='MIT Mini Cheetah physical platforms, flips and running-jump demonstrations.',overview='Plans an aerial motion once before launch, then tracks it with fast feedback.',order='Centroidal momentum model.',architecture='Nonlinear trajectory optimization + variational optimal feedback.')
checked(16,evidence='Hardware + simulation',setting='Physical box-launch diagonal jumps / barrel rolls; separate simulated double-backflip.',overview='A reduced dynamics stage chooses timing; full nonlinear optimization refines the body and limb trajectory.',order='Reduced rigid-body timing stage + full-body trajectory optimization.',architecture='Sequential two-level model-based optimization.')
checked(20,evidence='Hardware + simulation',setting='Uneven-terrain tests on two quadrupeds, according to the primary abstract.',overview='Couples body dynamics, foot kinematics and perception to plan directional jumps over uneven terrain.',order='Coupled kinodynamic planning; detailed state reduction not audited.',architecture='Warm-started trajectory optimization + perception.',verification='Primary abstract checked; timing and relocalization details retained from supplied RDF.')
checked(23,evidence='Hardware',setting='Quadruped real-world jumps with perturbed foot heights.',overview='Reinforcement learning extends optimized jump references to uncertain terrain and dynamics, while accounting for actuator limits.',order='TO reference + articulated robot training model; deployed policy has no explicit optimizer.',architecture='Hybrid trajectory-optimization-guided RL.',verification='Primary abstract checked. RDF year 2024 is the later publication label; linked preprint first appeared in 2020.')
checked(25,evidence='Hardware + simulation',setting='Solo 8 physical skill demonstrations; MPI author page confirms hardware backflip.',overview='WASABI learns an adversarial imitation reward from rough, partial demonstrations, including manually guided motions.',order='Articulated robot simulation for training; no online planning model.',architecture='Wasserstein adversarial imitation + RL.',video='https://is.mpg.de/dlg/en/projects/learning-agile-skills-via-adversarial-imitation-of-rough-partial-demonstrations',videoLabel='Author page & demonstrations',verification='Paper abstract and MPI author project checked.',sources=[{'url':'https://arxiv.org/abs/2206.11693','label':'Paper'},{'url':'https://is.mpg.de/dlg/en/projects/learning-agile-skills-via-adversarial-imitation-of-rough-partial-demonstrations','label':'MPI project'}])
checked(26,evidence='Hardware',setting='Physical Solo 8 after simulation training; controlled demonstrations.',overview='Tracks optimized references through learned policies and studies how feedforward design affects transfer.',order='TO-derived references; exact model order not audited.',architecture='Trajectory optimization + imitation RL.',achievement='Trot, front hop, 180° backflip and biped stepping transfer to physical Solo 8 without further adaptation.',verification='arXiv v3 abstract checked; 2022 is the first-preprint year.')
checked(28,evidence='Hardware · includes outdoors',setting='Physical omnidirectional jumps and repeated jumping on soft grass.',overview='A reference-free curriculum progresses from vertical jumps to directional and obstacle-crossing tasks.',order='Articulated simulation training; no explicit online planner.',architecture='Goal-conditioned RL with staged curriculum.')
checked(30,evidence='Simulation only',setting='Rigid and parallel-elastic robot simulations; hardware is explicitly future work.',overview='Imitate one coarse optimized jump, then train for varied targets and uneven ground.',order='Reduced-order TO demonstration + articulated simulation.',architecture='Example-guided RL and curriculum.',verification='Full-text conclusion checked; hardware is future work.')
checked(31,evidence='Hardware + simulation',setting='KLEIYN quadruped physical jump, backflip and lateral-flip demonstrations.',overview='Like a gymnastics spotter, simulated assistive forces make successful exploration easier and fade during training.',order='RL in articulated simulation; no explicit online planning model.',architecture='External-force curriculum; assistance decays to zero.',video='https://keitayoneda.github.io/kleiyn-efgcl/',videoLabel='Author project & videos',verification='Author project checked; physical skill demonstrations described separately from training.')
checked(32,evidence='Hardware · indoor + outdoor',setting='Publisher reports real-robot indoor and outdoor complex-terrain tests.',overview='Train with disturbances applied to both legs and body, using a learned disturbance generator and adaptation module.',order='No explicit deployed model-based optimizer described in abstract.',architecture='Adversarial RL + H∞ regularization + adaptation.',achievement='Publisher reports robust real-robot jumping under body and leg disturbances in indoor and outdoor tests.',gap='Full trial distributions and operating limits were not audited. H∞ regularization should not be treated as a universal hardware safety guarantee.',verification='Publisher abstract and method summary checked; full experiments not audited.',sources=[{'url':'https://www.sciencedirect.com/science/article/pii/S096706612500512X','label':'Publisher evidence'}])
checked(33,evidence='Hardware + simulation',setting='Mini Cheetah: physical drops up to 2 m; 8 m drops only in simulation.',overview='Jointly selects touchdown posture and reaction-force profiles without requiring a preset contact schedule.',order='Optimal landing model; detailed model order not independently audited.',architecture='Real-time model-based landing optimization.')
checked(34,evidence='Hardware + simulation',setting='Mini Cheetah reorientation experiments; controlled falling conditions.',overview='Compares ways to learn the output of a trajectory optimizer for feet-first reorientation.',order='TO teacher and learned trajectory outputs.',architecture='Supervised learning + trajectory optimization; not automatically RL.',verification='Primary abstract checked; numerical pitch range retained as RDF-reported.')
checked(37,evidence='Hardware',setting='Physical landings on rough / slippery ground and under disturbances.',overview='Relaxes reference tracking near touchdown so a learned policy can adapt the landing to the terrain.',order='TO reference plus learned control; exact order not audited.',architecture='Trajectory optimization + RL; terrain-adaptive landing reward.',verification='Primary abstract checked; planner restrictions retained from supplied RDF.')
checked(40,evidence='Hardware',setting='ANYmal physical obstacle-course navigation; curated parkour environment.',overview='A navigation policy chooses and commands locomotion skills, supported by learned obstacle reconstruction.',order='Articulated training simulation; no explicit deployed dynamics optimizer.',architecture='Hierarchical RL: perception, navigation and specialized skills.',verification='Primary abstract checked; hardware speed retained as RDF-reported.')
checked(41,evidence='Hardware',setting='Two physical low-cost quadruped platforms; obstacle-course tests.',overview='Uses a learning curriculum and distilled visual control to connect several obstacle-traversal behaviors.',order='Simulation-trained control; no explicit deployed planner.',architecture='RL curriculum + skill distillation + depth vision.',verification='Primary abstract checked; detailed skill list retained from supplied RDF.')
checked(42,evidence='Hardware',setting='Depth-camera quadruped tests on obstacle courses with varied properties.',overview='A single camera-conditioned policy learns precise traversal despite imperfect sensing and actuation.',order='Articulated training simulation; model-free deployed policy.',architecture='End-to-end visual RL at policy level.',verification='Primary abstract checked. Obstacle height is not airborne body clearance.')
checked(43,evidence='Hardware · controlled course',setting='Go1 with D435i depth camera; offboard Mac Mini inference.',overview='Combines learned terrain height prediction, a body-motion policy and model-based leg control.',order='Centroidal-level policy + leg controller.',architecture='Hierarchical hybrid; perception + RL + model-based tracking.',gap='Authors explicitly limit motion to the sagittal plane: no sideways/turning motions and no strategic path planning. Offboard inference is part of the tested setup.',video='https://yxyang.github.io/jumping_cod/',videoLabel='Project & experiment videos',verification='Full-text experimental setup and limitations checked.',sources=[{'url':'https://arxiv.org/html/2409.10923v1','label':'Paper: setup and conclusion'}])
checked(44,evidence='Earth-based gravity testbed',setting='SpaceBok Earth-based reduced-gravity rigs, including constrained motion.',environment='Moon-oriented research; not tested on the Moon.',overview='Elastic legs and a reaction wheel support repeated hopping when low gravity lengthens flight.',order='Model-based planning with elastic legs; source-specific model order not audited.',architecture='Leg control + reaction-wheel attitude stabilization.',achievement='ESA reports repetitive jumps up to 1.3 m in simulated lunar conditions. This is Earth-based gravity emulation, not a lunar field result.',gap='Constrained rigs do not validate unrestricted 3D hopping on regolith. SpaceBok is a research platform and is not space-qualified.',video='https://www.esa.int/Enabling_Support/Space_Engineering_Technology/Jumping_space_robot_flies_like_a_spacecraft',videoLabel='ESA tests & video',verification='ESA test report and ETH platform page checked; paper-specific jump metrics not independently audited.',sources=[{'url':'https://www.esa.int/Enabling_Support/Space_Engineering_Technology/Jumping_space_robot_flies_like_a_spacecraft','label':'ESA test report'},{'url':'https://rsl.ethz.ch/robots-media/spacebok.html/','label':'ETH platform status'}])
checked(45,evidence='Simulation + 2D hardware testbed',setting='SpaceBok physical 2D microgravity testbed; 3D behaviors in simulation.',environment='Low-gravity celestial-body target; experiments on Earth.',overview='Moves the legs to change aerial attitude, rather than relying on a reaction wheel.',order='Articulated simulation training; learned policy at deployment.',architecture='Deep RL for limb-driven flight and landing.',achievement='Learns 3D reorientation and low-gravity locomotion in simulation; transfers policies to SpaceBok on a 2D microgravity-emulation testbed.',gap='The physical test restricts motion to 2D. This does not establish free 3D control on the Moon, Mars, or under shorter Earth-gravity flight times.')
(R/'data/updates.json').write_text(json.dumps(U,ensure_ascii=False,indent=2))
A=[]
def add(id,title,year,group,method,url,overview,achievement,gap,evidence,setting,order,architecture,video='',verification='Primary abstract checked 29 Sep 2026.',environment='Earth gravity / terrestrial robotics.',sources=None):
 A.append(dict(id=id,title=title,year=year,group=group,method=method,url=url,overview=overview,achievement=achievement,gap=gap,evidence=evidence,setting=setting,order=order,architecture=architecture,video=video,videoLabel='Author project & videos',verification=verification,environment=environment,origin='Added in this survey',sources=sources or [{'url':url,'label':'Primary paper'}]))
g='Generative control & expert policies'
add('dial-mpc','Full-Order Sampling-Based MPC for Torque-Level Locomotion Control via Diffusion-Style Annealing','2024',g,'Model-based · full-order MPC','https://arxiv.org/abs/2409.15610','DIAL-MPC refines sampled actions online using diffusion-inspired annealing. It does not train a diffusion policy.','Go2 hardware performs sequential jumping with a 7 kg payload. Appendix setup uses 50 Hz planning and 200 Hz low-level commands.','Fast parallel simulation and a short planning horizon constrain the approach. Desktop computation and motion capture limit claims about autonomous field deployment.','Hardware · lab','Go2; offboard RTX 4090 desktop, Ethernet and motion capture.','Full-order articulated dynamics.','Sampling-based receding-horizon control; direct torque output.','https://github.com/LeCAR-Lab/dial-mpc/blob/main/README.md',verification='Full text: Fig. 7, conclusion and Appendix A checked; preprint 2024 / ICRA 2025.',sources=[{'url':'https://arxiv.org/html/2409.15610v1','label':'Full text and setup'}])
add('diffuseloco','DiffuseLoco: Real-Time Legged Locomotion Control with Diffusion from Offline Datasets','2024',g,'Diffusion · offline imitation','https://arxiv.org/abs/2404.19264','Learns a multi-skill locomotion policy from offline data, using a receding action horizon.','Reports real quadruped deployment, transitions between locomotion skills, and edge-device execution.','This demonstrates locomotion-policy synthesis; it does not establish arbitrary precision flips or terrain-aware pronking sequences. Dataset coverage and action-generation latency remain relevant.','Hardware','Quadruped physical locomotion demonstrations; controlled evaluations.','No explicit online dynamics optimizer; data-driven action policy.','Offline diffusion policy with receding-horizon execution.','https://diffuselo.co/',verification='Author project and abstract checked; CoRL 2024.')
add('contact-diffusion','Diffusion-based learning of contact plans for agile locomotion','2024',g,'Diffusion · MCTS · NMPC','https://arxiv.org/abs/2403.03639','Search generates feasible contact plans; diffusion learns their multiple possible solutions and supplies a whole-body controller.','Simulated Solo12 selects contact sequences for jumping on sparse stepping stones.','Hardware implementation remains future work in v5. Known terrain, restricted gait search and low success on a difficult changing-stone task limit generalization claims.','Simulation only','Solo12 simulation; not a physical stepping-stone demonstration.','Whole-body nonlinear MPC.','High-level diffusion contact planner + low-level NMPC.','',verification='v5 full text, including conclusion, checked (23 June 2025). First preprint 2024 used a different title.',sources=[{'url':'https://arxiv.org/html/2403.03639v5','label':'v5 full text'}])
add('dynaflow','DynaFlow: Dynamics-embedded Flow Matching for Physically Consistent Motion Generation from State-only Demonstrations','2025',g,'Flow matching · differentiable simulation','https://arxiv.org/abs/2509.19804','Maps generated actions through a differentiable simulator so learning can use state-only demonstrations.','Physical Go1 reproduces varied gaits and stylistic motions; the project reports long-horizon open-loop execution.','Consistency is with the embedded model. It does not guarantee disturbance recovery in the real world or establish a closed-loop acrobatic pronking system.','Hardware','Go1 physical motion demonstrations.','Dynamics embedded through differentiable simulation.','Flow-matching action generation trained through a simulator.','https://sowoolee.github.io/dynaflow/',verification='Author project checked; 2025 preprint / ICRA 2026.',sources=[{'url':'https://sowoolee.github.io/dynaflow/','label':'Author method and experiments'}])
add('dmloco','Integrating Diffusion-based Multi-task Learning with Online Reinforcement Learning for Robust Quadruped Robot Control','2025',g,'Diffusion · PPO fine-tuning','https://arxiv.org/abs/2507.05674','DMLoco combines offline multi-task diffusion training with reinforcement-learning refinement.','The abstract reports language-conditioned skills, more stable task transitions and onboard inference at 50 Hz.','This is adjacent multi-skill locomotion evidence. The abstract alone does not establish acrobatic landing accuracy or unseen-terrain pronking reliability.','Hardware reported','Real-world deployment reported in abstract; detailed test setting not audited.','No explicit online physics planner described.','Diffusion pretraining + PPO in simulation + onboard policy.',verification='arXiv v2 abstract checked (September 2025); experimental tables not audited.')
add('moe-parkour','Quadruped Parkour Learning: Sparsely Gated Mixture of Experts with Visual Input','2026',g,'RL · sparse mixture of experts','https://arxiv.org/abs/2604.19344','A sparse expert network allocates computation conditionally inside a vision-based parkour policy.','On a 32 cm box, MoE succeeds in 10/10 trials versus 5/10 for an MLP with matched active parameters. Outdoor obstacle demonstrations are included.','Small trial counts do not establish field reliability. Expert selection adds tuning. The reported speed comparison uses batch size 6000, not simply onboard latency.','Hardware · lab + outdoor','Go2 + D435f camera; policy runs offboard on RTX 2060.','Simulation-trained policy, no explicit online dynamics optimization.','Depth-conditioned RL with sparse MoE actor.',verification='Full text: Table III, hardware setup, outdoor tests and conclusion checked.',sources=[{'url':'https://arxiv.org/html/2604.19344v1','label':'Experiments and limitations'}])
add('abot','Behavior Foundations for Quadruped Robots: ABot-C0 Technical Report','2026',g,'Flow matching · multi-policy system','https://arxiv.org/abs/2607.07370','Transfers the large-data motion-tracking recipe prominent in humanoids to quadruped behavior learning.','Reports 16,074 feasible motion clips, a flow-matching motion-tracking policy, and real-world navigation / interaction experiments.','Generalist tracking and urban navigation are not quantitative proof of arbitrary flips, precise repeated landings, or low-gravity performance. Independent replication is not assessed.','Hardware reported','Urban-terrain navigation and interaction; detailed experiment audit pending.','Data-driven tracking; underlying simulator order not audited.','Flow tracking + privileged-to-perceptive locomotion + multi-policy coordination.',verification='July 2026 arXiv v2 technical-report abstract checked; author claims, not independent replication.')
g='Low gravity and space robotics'
# Match the existing low-gravity group rather than fragment it.
g=raw[43]['tags'][1]
add('spacebok-design','SpaceBok: A Dynamic Legged Robot for Space Exploration','2019',g,'Model-based · elastic hardware','https://doi.org/10.1109/ICRA.2019.8794136','A purpose-built quadruped uses leg geometry and parallel elasticity for powerful hopping.','The primary paper reports physical walking, trotting and pronking, with single jumps up to 1.05 m. Lunar-pronking predictions are simulated.','Earth jumping does not establish operation in lunar dust, vacuum or thermal extremes. ETH describes the platform as not space-graded.','Hardware + low-gravity simulation','Earth-based physical robot; simulated lunar locomotion.','Elastic mechanism and model-based control; order not audited.','Hardware/control co-design.','https://www.esa.int/Enabling_Support/Space_Engineering_Technology/Jumping_space_robot_flies_like_a_spacecraft',verification='ETH-hosted paper and ETH platform description checked.',environment='Extraterrestrial motivation; hardware tests on Earth.',sources=[{'url':'https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/384203/ICRA19_0651_FI.pdf?isAllowed=y&sequence=1','label':'ETH paper'},{'url':'https://rsl.ethz.ch/robots-media/spacebok.html/','label':'ETH platform'}])
add('spacehopper','SpaceHopper: A Small-Scale Legged Robot for Exploring Low-Gravity Celestial Bodies','2024',g,'RL · limb-based attitude control','https://arxiv.org/abs/2403.02831','A three-legged robot explores how moving limbs can orient the body during long low-gravity flights. This is related work, not a quadruped.','Physical tests use a rotational gimbal and counterweight setup. Six-metre commanded jumps are reported in simulated Ceres gravity (0.029 g).','The simulated distance is not a hardware jump record. Gimbal and counterweight tests do not establish autonomous flight and landing on an asteroid.','Hardware testbed + simulation','5.2 kg three-legged robot; Earth gimbal / counterweight rigs.','Articulated robot simulation for RL.','Learned leg-based aerial reorientation.',environment='Asteroid / moon target; simulation and Earth-based tests.')
g='Bipedal connections & foundations'
add('deepmimic','DeepMimic: Example-Guided Deep Reinforcement Learning of Physics-Based Character Skills','2018',g,'RL · motion imitation','https://doi.org/10.1145/3197517.3201311','A shared imitation-plus-task formulation learns diverse motions in simulated characters.','Demonstrates acrobatics, locomotion and recovery across simulated human, Atlas, dinosaur and dragon characters.','A simulated Atlas character is not a physical Atlas experiment. This provides methodological ancestry, not evidence of quadruped-to-biped hardware policy transfer.','Simulation only','Physics-based character animation; no physical hardware demonstration.','Full articulated character simulation.','Reference-motion tracking through RL.','https://xbpeng.github.io/projects/DeepMimic/index.html',verification='Author project and primary paper checked.',sources=[{'url':'https://xbpeng.github.io/projects/DeepMimic/index.html','label':'Author project'}])
add('animal-imitation','Learning Agile Robotic Locomotion Skills by Imitating Animals','2020',g,'RL · imitation · sim-to-real','https://arxiv.org/abs/2004.00784','Retargets animal motion references to learn robot skills, extending motion-imitation ideas to physical quadrupeds.','Reports physical quadruped locomotion, dynamic hops and turns from reference-guided learning.','Reference availability, retargeting and simulator mismatch matter. It does not show that a humanoid controller can be copied unchanged onto a quadruped.','Hardware','Physical quadruped demonstrations after simulation training.','Articulated simulation; learned policy at deployment.','Motion retargeting + imitation RL + sim-to-real.','https://xbpeng.github.io/projects/Robotic_Imitation/index.html',verification='Primary abstract and author project checked.')
add('asap','ASAP: Aligning Simulation and Real-World Physics for Learning Agile Humanoid Whole-Body Skills','2025',g,'RL · imitation · residual sim alignment','https://arxiv.org/abs/2502.01143','Uses real robot rollouts to learn an action correction inside the simulator, then fine-tunes the motion policy.','Unitree G1 hardware demonstrates agile human-like skills; author examples include forward and sideways jumps and a jump with rotation.','Requires real-world data collection. This is a humanoid method with related ingredients, not demonstrated quadruped-to-humanoid acrobatic transfer.','Hardware','Unitree G1 physical demonstrations and simulator-transfer experiments.','Articulated simulation corrected by learned delta actions.','Two-stage motion imitation and sim-to-real fine-tuning.','https://agile.human2humanoid.com/',verification='Author project and primary abstract checked; RSS 2025.')
add('beyondmimic','BeyondMimic: From Motion Tracking to Versatile Humanoid Control via Guided Diffusion','2025',g,'RL tracking · guided diffusion','https://arxiv.org/abs/2508.08241','First learn dynamic motion tracking, then distill selected motion policies into a guided diffusion policy.','The tracking pipeline demonstrates jumping spins and cartwheels; diffusion demonstrations include waypoint following, teleoperation and obstacle avoidance.','Do not attribute every acrobatic tracker result to the unified diffusion controller. The project uses motion capture for some navigation / state-estimation demonstrations.','Hardware','Humanoid physical demonstrations; motion-capture-assisted downstream tests.','Articulated training simulation; distilled generative policy.','RL motion tracking + diffusion distillation + test-time guidance.','https://beyondmimic.github.io/',verification='Author project and 2025 preprint abstract checked; results separated by pipeline stage.')
(R/'data/additions.json').write_text(json.dumps(A,ensure_ascii=False,indent=2))
print('Curated',len(U),'RDF records and',len(A),'new papers')
